/* 
 * Polygon API
 *
 * The future of fintech.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PolygonIO.Client.SwaggerDateConverter;

namespace PolygonIO.Model
{
    /// <summary>
    /// AllOfCryptoSnapshotTickerTickerLastTrade
    /// </summary>
    [DataContract]
        public partial class AllOfCryptoSnapshotTickerTickerLastTrade :  IEquatable<AllOfCryptoSnapshotTickerTickerLastTrade>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AllOfCryptoSnapshotTickerTickerLastTrade" /> class.
        /// </summary>
        /// <param name="x">The exchange that this crypto trade happened on.   See &lt;a href&#x3D;\&quot;https://polygon.io/docs/get_v1_meta_crypto-exchanges_anchor\&quot;&gt;Crypto Exchanges&lt;/a&gt; for a mapping of exchanges to IDs. .</param>
        public AllOfCryptoSnapshotTickerTickerLastTrade(int? x = default(int?))
        {
            this.X = x;
        }
        
        /// <summary>
        /// The exchange that this crypto trade happened on.   See &lt;a href&#x3D;\&quot;https://polygon.io/docs/get_v1_meta_crypto-exchanges_anchor\&quot;&gt;Crypto Exchanges&lt;/a&gt; for a mapping of exchanges to IDs. 
        /// </summary>
        /// <value>The exchange that this crypto trade happened on.   See &lt;a href&#x3D;\&quot;https://polygon.io/docs/get_v1_meta_crypto-exchanges_anchor\&quot;&gt;Crypto Exchanges&lt;/a&gt; for a mapping of exchanges to IDs. </value>
        [DataMember(Name="x", EmitDefaultValue=false)]
        public int? X { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AllOfCryptoSnapshotTickerTickerLastTrade {\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AllOfCryptoSnapshotTickerTickerLastTrade);
        }

        /// <summary>
        /// Returns true if AllOfCryptoSnapshotTickerTickerLastTrade instances are equal
        /// </summary>
        /// <param name="input">Instance of AllOfCryptoSnapshotTickerTickerLastTrade to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AllOfCryptoSnapshotTickerTickerLastTrade input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.X == input.X ||
                    (this.X != null &&
                    this.X.Equals(input.X))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.X != null)
                    hashCode = hashCode * 59 + this.X.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
