/* 
 * Polygon API
 *
 * The future of fintech.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PolygonIO.Client.SwaggerDateConverter;

namespace PolygonIO.Model
{
    /// <summary>
    /// InlineResponse20020
    /// </summary>
    [DataContract]
        public partial class InlineResponse20020 :  IEquatable<InlineResponse20020>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20020" /> class.
        /// </summary>
        /// <param name="condition">Polygon.io&#x27;s mapping for condition codes.  For more information, see our &lt;a href&#x3D;\&quot;https://polygon.io/glossary/us/stocks/trade-conditions\&quot; alt&#x3D;\&quot;Trade Conditions Glossary\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Trade Conditions Glossary&lt;/a&gt;. .</param>
        public InlineResponse20020(string condition = default(string))
        {
            this.Condition = condition;
        }
        
        /// <summary>
        /// Polygon.io&#x27;s mapping for condition codes.  For more information, see our &lt;a href&#x3D;\&quot;https://polygon.io/glossary/us/stocks/trade-conditions\&quot; alt&#x3D;\&quot;Trade Conditions Glossary\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Trade Conditions Glossary&lt;/a&gt;. 
        /// </summary>
        /// <value>Polygon.io&#x27;s mapping for condition codes.  For more information, see our &lt;a href&#x3D;\&quot;https://polygon.io/glossary/us/stocks/trade-conditions\&quot; alt&#x3D;\&quot;Trade Conditions Glossary\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Trade Conditions Glossary&lt;/a&gt;. </value>
        [DataMember(Name="condition", EmitDefaultValue=false)]
        public string Condition { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20020 {\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20020);
        }

        /// <summary>
        /// Returns true if InlineResponse20020 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20020 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20020 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Condition == input.Condition ||
                    (this.Condition != null &&
                    this.Condition.Equals(input.Condition))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Condition != null)
                    hashCode = hashCode * 59 + this.Condition.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
