/* 
 * Polygon API
 *
 * The future of fintech.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PolygonIO.Client.SwaggerDateConverter;

namespace PolygonIO.Model
{
    /// <summary>
    /// MarketStatusCurrencies
    /// </summary>
    [DataContract]
        public partial class MarketStatusCurrencies :  IEquatable<MarketStatusCurrencies>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketStatusCurrencies" /> class.
        /// </summary>
        /// <param name="fx">The status of the forex market..</param>
        /// <param name="crypto">The status of the crypto market..</param>
        public MarketStatusCurrencies(string fx = default(string), string crypto = default(string))
        {
            this.Fx = fx;
            this.Crypto = crypto;
        }
        
        /// <summary>
        /// The status of the forex market.
        /// </summary>
        /// <value>The status of the forex market.</value>
        [DataMember(Name="fx", EmitDefaultValue=false)]
        public string Fx { get; set; }

        /// <summary>
        /// The status of the crypto market.
        /// </summary>
        /// <value>The status of the crypto market.</value>
        [DataMember(Name="crypto", EmitDefaultValue=false)]
        public string Crypto { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MarketStatusCurrencies {\n");
            sb.Append("  Fx: ").Append(Fx).Append("\n");
            sb.Append("  Crypto: ").Append(Crypto).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MarketStatusCurrencies);
        }

        /// <summary>
        /// Returns true if MarketStatusCurrencies instances are equal
        /// </summary>
        /// <param name="input">Instance of MarketStatusCurrencies to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MarketStatusCurrencies input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Fx == input.Fx ||
                    (this.Fx != null &&
                    this.Fx.Equals(input.Fx))
                ) && 
                (
                    this.Crypto == input.Crypto ||
                    (this.Crypto != null &&
                    this.Crypto.Equals(input.Crypto))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Fx != null)
                    hashCode = hashCode * 59 + this.Fx.GetHashCode();
                if (this.Crypto != null)
                    hashCode = hashCode * 59 + this.Crypto.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
