/* 
 * Polygon API
 *
 * The future of fintech.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PolygonIO.Client.SwaggerDateConverter;

namespace PolygonIO.Model
{
    /// <summary>
    /// PaginationHooksBase
    /// </summary>
    [DataContract]
        public partial class PaginationHooksBase :  IEquatable<PaginationHooksBase>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaginationHooksBase" /> class.
        /// </summary>
        /// <param name="nextPagePath">If present, this value can be used to fetch the next page of data by appending this to the API url host..</param>
        public PaginationHooksBase(string nextPagePath = default(string))
        {
            this.NextPagePath = nextPagePath;
        }
        
        /// <summary>
        /// If present, this value can be used to fetch the next page of data by appending this to the API url host.
        /// </summary>
        /// <value>If present, this value can be used to fetch the next page of data by appending this to the API url host.</value>
        [DataMember(Name="next_page_path", EmitDefaultValue=false)]
        public string NextPagePath { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaginationHooksBase {\n");
            sb.Append("  NextPagePath: ").Append(NextPagePath).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaginationHooksBase);
        }

        /// <summary>
        /// Returns true if PaginationHooksBase instances are equal
        /// </summary>
        /// <param name="input">Instance of PaginationHooksBase to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaginationHooksBase input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NextPagePath == input.NextPagePath ||
                    (this.NextPagePath != null &&
                    this.NextPagePath.Equals(input.NextPagePath))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NextPagePath != null)
                    hashCode = hashCode * 59 + this.NextPagePath.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
