/* 
 * Polygon API
 *
 * The future of fintech.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PolygonIO.Client.SwaggerDateConverter;

namespace PolygonIO.Model
{
    /// <summary>
    /// TickerTypesResults
    /// </summary>
    [DataContract]
        public partial class TickerTypesResults :  IEquatable<TickerTypesResults>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TickerTypesResults" /> class.
        /// </summary>
        /// <param name="types">types.</param>
        /// <param name="indexTypes">indexTypes.</param>
        public TickerTypesResults(TickerTypesResultsTypes types = default(TickerTypesResultsTypes), TickerTypesResultsIndexTypes indexTypes = default(TickerTypesResultsIndexTypes))
        {
            this.Types = types;
            this.IndexTypes = indexTypes;
        }
        
        /// <summary>
        /// Gets or Sets Types
        /// </summary>
        [DataMember(Name="types", EmitDefaultValue=false)]
        public TickerTypesResultsTypes Types { get; set; }

        /// <summary>
        /// Gets or Sets IndexTypes
        /// </summary>
        [DataMember(Name="indexTypes", EmitDefaultValue=false)]
        public TickerTypesResultsIndexTypes IndexTypes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TickerTypesResults {\n");
            sb.Append("  Types: ").Append(Types).Append("\n");
            sb.Append("  IndexTypes: ").Append(IndexTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TickerTypesResults);
        }

        /// <summary>
        /// Returns true if TickerTypesResults instances are equal
        /// </summary>
        /// <param name="input">Instance of TickerTypesResults to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TickerTypesResults input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Types == input.Types ||
                    (this.Types != null &&
                    this.Types.Equals(input.Types))
                ) && 
                (
                    this.IndexTypes == input.IndexTypes ||
                    (this.IndexTypes != null &&
                    this.IndexTypes.Equals(input.IndexTypes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Types != null)
                    hashCode = hashCode * 59 + this.Types.GetHashCode();
                if (this.IndexTypes != null)
                    hashCode = hashCode * 59 + this.IndexTypes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
